export const deluxeRooms = [
  {
    id: 1001,
    image: "coolhoteldeluxe.jpg",
    title: "Classic Single Room",
    adults: 2,
    size: 410,
    subTitle: "All our Room have big windows to help you take a broad..",
    price: 49,
  },
  {
    id: 1002,
    image: "coolhoteldeluxe.jpg",
    title: "Couple Room",
    adults: 2,
    size: 410,
    subTitle: "All our Room have big windows to help you take a broad..",
    price: 49,
  },
  {
    id: 1003,
    image: "coolhoteldeluxe.jpg",
    title: "Deluxe Suite Room",
    adults: 2,
    size: 410,
    subTitle: "All our Room have big windows to help you take a broad..",
    price: 49,
  },
  {
    id: 1004,
    image: "coolhoteldeluxe.jpg",
    title: "Deluxe Suite Room",
    adults: 2,
    size: 410,
    subTitle: "All our Room have big windows to help you take a broad..",
    price: 49,
  },
  {
    id: 1005,
    image: "coolhoteldeluxe.jpg",
    title: "Deluxe Suite Room",
    adults: 2,
    size: 410,
    subTitle: "All our Room have big windows to help you take a broad..",
    price: 49,
  },
  {
    id: 1006,
    image: "coolhoteldeluxe.jpg",
    title: "Deluxe Suite Room",
    adults: 2,
    size: 410,
    subTitle: "All our Room have big windows to help you take a broad..",
    price: 49,
  },
  {
    id: 1007,
    image: "coolhoteldeluxe.jpg",
    title: "Deluxe Suite Room",
    adults: 2,
    size: 410,
    subTitle: "All our Room have big windows to help you take a broad..",
    price: 49,
  },
  {
    id: 1008,
    image: "coolhoteldeluxe.jpg",
    title: "Deluxe Suite Room",
    adults: 2,
    size: 410,
    subTitle: "All our Room have big windows to help you take a broad..",
    price: 49,
  },
  {
    id: 1009,
    image: "coolhoteldeluxe.jpg",
    title: "Deluxe Suite Room",
    adults: 2,
    size: 410,
    subTitle: "All our Room have big windows to help you take a broad..",
    price: 49,
  },
  {
    id: 1010,
    image: "coolhoteldeluxe.jpg",
    title: "Deluxe Suite Room",
    adults: 2,
    size: 410,
    subTitle: "All our Room have big windows to help you take a broad..",
    price: 49,
  },
];

export const executiveRooms = [
  {
    id: 2001,
    image: "coolhotelexecutive.jpg",
    title: "Classic Single Room",
    adults: 2,
    size: 410,
    subTitle: "All our Room have big windows to help you take a broad..",
    price: 49,
  },
  {
    id: 2002,
    image: "coolhotelexecutive.jpg",
    title: "Couple Room",
    adults: 2,
    size: 410,
    subTitle: "All our Room have big windows to help you take a broad..",
    price: 49,
  },
  {
    id: 2003,
    image: "coolhotelexecutive.jpg",
    title: "Deluxe Suite Room",
    adults: 2,
    size: 410,
    subTitle: "All our Room have big windows to help you take a broad..",
    price: 49,
  },
  {
    id: 2004,
    image: "coolhotelexecutive.jpg",
    title: "Deluxe Suite Room",
    adults: 2,
    size: 410,
    subTitle: "All our Room have big windows to help you take a broad..",
    price: 49,
  },
  {
    id: 2005,
    image: "coolhotelexecutive.jpg",
    title: "Deluxe Suite Room",
    adults: 2,
    size: 410,
    subTitle: "All our Room have big windows to help you take a broad..",
    price: 49,
  },
  {
    id: 2006,
    image: "coolhotelexecutive.jpg",
    title: "Deluxe Suite Room",
    adults: 2,
    size: 410,
    subTitle: "All our Room have big windows to help you take a broad..",
    price: 49,
  },
  {
    id: 2007,
    image: "coolhotelexecutive.jpg",
    title: "Deluxe Suite Room",
    adults: 2,
    size: 410,
    subTitle: "All our Room have big windows to help you take a broad..",
    price: 49,
  },
  {
    id: 2008,
    image: "coolhotelexecutive.jpg",
    title: "Deluxe Suite Room",
    adults: 2,
    size: 410,
    subTitle: "All our Room have big windows to help you take a broad..",
    price: 49,
  },
  {
    id: 2009,
    image: "coolhotelexecutive.jpg",
    title: "Deluxe Suite Room",
    adults: 2,
    size: 410,
    subTitle: "All our Room have big windows to help you take a broad..",
    price: 49,
  },
  {
    id: 2010,
    image: "coolhotelexecutive.jpg",
    title: "Deluxe Suite Room",
    adults: 2,
    size: 410,
    subTitle: "All our Room have big windows to help you take a broad..",
    price: 49,
  },
  {
    id: 2011,
    image: "coolhotelexecutive.jpg",
    title: "Deluxe Suite Room",
    adults: 2,
    size: 410,
    subTitle: "All our Room have big windows to help you take a broad..",
    price: 49,
  },
  {
    id: 2012,
    image: "coolhotelexecutive.jpg",
    title: "Deluxe Suite Room",
    adults: 2,
    size: 410,
    subTitle: "All our Room have big windows to help you take a broad..",
    price: 49,
  },
  {id: 2013,
    image: "coolhotelexecutive.jpg",
    title: "Deluxe Suite Room",
    adults: 2,
    size: 410,
    subTitle: "All our Room have big windows to help you take a broad..",
    price: 49,
  },
  {
    id: 2014,
    image: "coolhotelexecutive.jpg",
    title: "Deluxe Suite Room",
    adults: 2,
    size: 410,
    subTitle: "All our Room have big windows to help you take a broad..",
    price: 49,
  },
  {
    id: 2015,
    image: "coolhotelexecutive.jpg",
    title: "Deluxe Suite Room",
    adults: 2,
    size: 410,
    subTitle: "All our Room have big windows to help you take a broad..",
    price: 49,
  },
  {
    id: 2016,
    image: "coolhotelexecutive.jpg",
    title: "Deluxe Suite Room",
    adults: 2,
    size: 410,
    subTitle: "All our Room have big windows to help you take a broad..",
    price: 49,
  },
];

export const luxuryRooms = [
  {
    id: 3001,
    image: "coolhotelluxury.jpg",
    title: "Classic Single Room",
    adults: 2,
    size: 410,
    subTitle: "All our Room have big windows to help you take a broad..",
    price: 49,
  },
  {
    id: 3002,
    image: "coolhotelluxury.jpg",
    title: "Couple Room",
    adults: 2,
    size: 410,
    subTitle: "All our Room have big windows to help you take a broad..",
    price: 49,
  },
  {
    id: 3003,
    image: "coolhotelluxury.jpg",
    title: "Deluxe Suite Room",
    adults: 2,
    size: 410,
    subTitle: "All our Room have big windows to help you take a broad..",
    price: 49,
  },
  {
    id: 3004,
    image: "coolhotelluxury.jpg",
    title: "Deluxe Suite Room",
    adults: 2,
    size: 410,
    subTitle: "All our Room have big windows to help you take a broad..",
    price: 49,
  },
  {
    id: 3005,
    image: "coolhotelluxury.jpg",
    title: "Deluxe Suite Room",
    adults: 2,
    size: 410,
    subTitle: "All our Room have big windows to help you take a broad..",
    price: 49,
  },
  {
    id: 3006,
    image: "coolhotelluxury.jpg",
    title: "Deluxe Suite Room",
    adults: 2,
    size: 410,
    subTitle: "All our Room have big windows to help you take a broad..",
    price: 49,
  },
  {
    id: 3007,
    image: "coolhotelluxury.jpg",
    title: "Deluxe Suite Room",
    adults: 2,
    size: 410,
    subTitle: "All our Room have big windows to help you take a broad..",
    price: 49,
  },
];

export const standardRooms = [
  {
    id: 4001,
    image: "coolhotelstandard.jpg",
    title: "Classic Single Room",
    adults: 2,
    size: 410,
    subTitle: "All our Room have big windows to help you take a broad..",
    price: 49,
  },
  {
    id: 4002,
    image: "coolhotelstandard.jpg",
    title: "Couple Room",
    adults: 2,
    size: 410,
    subTitle: "All our Room have big windows to help you take a broad..",
    price: 49,
  },
  {
    id: 4003,
    image: "coolhotelstandard.jpg",
    title: "Deluxe Suite Room",
    adults: 2,
    size: 410,
    subTitle: "All our Room have big windows to help you take a broad..",
    price: 49,
  },
  {
    id: 4004,
    image: "coolhotelstandard.jpg",
    title: "Deluxe Suite Room",
    adults: 2,
    size: 410,
    subTitle: "All our Room have big windows to help you take a broad..",
    price: 49,
  },
  {
    id: 4005,
    image: "coolhotelstandard.jpg",
    title: "Deluxe Suite Room",
    adults: 2,
    size: 410,
    subTitle: "All our Room have big windows to help you take a broad..",
    price: 49,
  },
  {
    id: 4006,
    image: "coolhotelstandard.jpg",
    title: "Deluxe Suite Room",
    adults: 2,
    size: 410,
    subTitle: "All our Room have big windows to help you take a broad..",
    price: 49,
  },
  {
    id: 4007,
    image: "coolhotelstandard.jpg",
    title: "Deluxe Suite Room",
    adults: 2,
    size: 410,
    subTitle: "All our Room have big windows to help you take a broad..",
    price: 49,
  },
];
